server:
  port: 8080

spring:
  application:
    name: WebService
  cloud:
    openfeign:
      client:
        config:
          user-service:
            url: http://localhost:8081/users
          auth-service:
            url: http://localhost:8081/auth
          cars-models-service:
            url: http://localhost:8082/cars
          cars-types-service:
            url: http://localhost:8082/cars
          cars-service:
            url: http://localhost:8082/cars
jwt:
  secret: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
  lifetime: 360000000