server:
  port: 8081

spring:
  application:
    name: UserService
  datasource:
    url: jdbc:postgresql://localhost:5433/users-db
    username: sa
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
jwt:
  secret: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
  lifetime: 360000000