version: '3'

services:
  postgres_user:
    image: 'postgres:13.2-alpine'
    container_name: 'user-postgres'
    ports:
      - "5433:5432"
    environment:
      - 'POSTGRES_USER=sa'
      - 'POSTGRES_PASSWORD=123'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=users-db'
    volumes:
      - './.containers/usersDB:/var/lib/postgresql/data'


#  postgres_user:
#    image: 'postgres:13.2-alpine'
#    container_name: 'user-postgres'
#    ports:
#      - "5432:5432"
#    environment:
#      - 'POSTGRES_USER=sa'
#      - 'POSTGRES_PASSWORD=123'
#      - 'POSTGRES_HOST_AUTH_METHOD=trust'
#      - 'POSTGRES_DB=users-db'
#    volumes:
#      - './.containers/usersDB:/var/lib/postgresql/data'

